### ISSUE TITLE
Stabilized palm and finger positions

### ISSUE THREAD

**Issue by omarwagih** [spren9er/threeleapcontrols#1]
Great library! Would be nice to optionally have stabilized positions used instead of the raw. This is a simple substitution `.palmPosition` to `stabilizedPalmPosition` and `tipPosition` to `stabilizedTipPosition`. I have manually changed this in my local version but perhaps it might be useful for the general public as a parameter.
Cheers

**Comment by SeeDoubleYou** [comment]
I've created a pull request. I've added option to use the stabilized position. See https://github.com/torstensprenger/threeleapcontrols/pull/2
